branch-defaults:
  default:
    environment: x23141000-lockrental-cpp
    group_suffix: null
global:
  application_name: Lockrental
  branch: null
  default_ec2_keyname: gamesh
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: MSCCLOUD-250738637992
  repository: null
  sc: null
  workspace_type: Application
